;; Key-audit diff (migration-scoped; see MIGRATION.org "Key clusters").
;; Compares the Doom and lab binding dumps against the key-decisions.edn
;; ledger, writes an org report to the cache dir, prints per-cluster open
;; counts.  Run from the repo root: bb keydiff
;;
;; Known limit: anonymous lambdas dump as "<lambda>" on both sides, so two
;; different lambdas on the same key compare equal.

(require '[clojure.edn :as edn]
         '[clojure.java.io :as io]
         '[clojure.string :as str])

(def cache-dir (str (System/getProperty "user.home") "/.emacs.d/.local/.cache/"))
(def doom-dump (or (System/getenv "KEYDIFF_DOOM") (str cache-dir "doom-keys.eld")))
(def lab-dump (or (System/getenv "KEYDIFF_LAB") (str cache-dir "lab-keys.eld")))
(def ledger-file "key-decisions.edn")
(def report-file (str cache-dir "keydiff.org"))

(defn fail [msg]
  (binding [*out* *err*] (println msg))
  (System/exit 2))

(defn read-dump [path side]
  (when-not (.exists (io/file path))
    (fail (str "keydiff: missing " side " dump at " path
               (if (= side "lab")
                 " - run: bb keydump"
                 " - run the dump-bindings walker in the live Doom session"))))
  (into {}
        (for [line (str/split-lines (slurp path))
              :when (not (str/blank? line))
              :let [[g k c & flags] (edn/read-string line)]]
          [[g k] {:cmd c
                  :void? (boolean (some #{:void} flags))
                  :void-suffix? (boolean (some #{:void-suffix} flags))}])))

(defn read-ledger []
  (if (.exists (io/file ledger-file))
    (or (edn/read-string (slurp ledger-file)) {})
    {}))

(defn cluster [[group k]]
  (if (= group "leader")
    (let [[a b] (str/split k #" ")]
      (if b (str a " " b) a))
    (str group " " (first (str/split k #" ")))))

(defn resolution
  "Classify a differing entry given its ledger decision."
  [{:keys [status decision lab-void? lab-void-suffix?]}]
  (let [d (:status decision)
        broken? (or lab-void? lab-void-suffix?)] ; void cmd or rotted transient
    (cond
      (and broken? (= d :ported)) :regression ; claimed ported, actually broken
      (and broken? (= d :deferred)) :deferred ; known: waits on a module
      broken? :broken
      (#{:dropped :improved :deferred} d) d
      (= d :ported) :regression      ; claimed ported, still differs
      (= status :lab-only) :lab-only ; lab additions, informational
      :else :open)))

(defn org-entry [{:keys [k doom lab status lab-void? lab-void-suffix? decision]}]
  (let [[g kd] k
        lab-str (str "=" lab "="
                     (when lab-void? " [void]")
                     (when lab-void-suffix? " [void-suffix]"))
        line (case status
               :bound-void (format "- =%s= (%s) :: =%s= bound on both sides, %s in lab"
                                   kd g doom
                                   (if lab-void? "void" "void transient suffixes"))
               :missing (format "- =%s= (%s) :: doom =%s=, lab unbound" kd g doom)
               :mismatch (format "- =%s= (%s) :: doom =%s=, lab %s" kd g doom lab-str)
               :lab-only (format "- =%s= (%s) :: lab-only %s" kd g lab-str))]
    (if-let [note (:note decision)]
      (str line " - " note)
      line)))

(defn -main []
  (let [doom (read-dump doom-dump "doom")
        lab (read-dump lab-dump "lab")
        ledger (read-ledger)
        entries (for [k (sort-by (fn [[g kd]] (str g " " kd))
                                 (set (concat (keys doom) (keys lab))))
                      :let [d (get-in doom [k :cmd])
                            l (get-in lab [k :cmd])
                            lab-void? (get-in lab [k :void?])
                            lab-void-suffix? (get-in lab [k :void-suffix?])]
                      :when (or (not= d l) lab-void? lab-void-suffix?)]
                  (let [status (cond (and d l (= d l)) :bound-void
                                     (and d l) :mismatch
                                     d :missing
                                     :else :lab-only)
                        e {:k k :doom d :lab l :status status :lab-void? lab-void?
                           :lab-void-suffix? lab-void-suffix?
                           :decision (get ledger k) :cluster (cluster k)}]
                    (assoc e :resolution (resolution e))))
        by-cluster (group-by :cluster entries)
        counts (fn [es] (frequencies (map :resolution es)))
        total (counts entries)]
    (io/make-parents report-file)
    (spit report-file
          (with-out-str
            (println "#+title: Key audit: Doom -> lab")
            (println (str "# generated by bb keydiff on " (java.time.LocalDate/now)))
            (println (str "# verdicts live in " ledger-file
                          " - :ported :improved :dropped :deferred"))
            (println)
            (doseq [[c es] (sort-by key by-cluster)
                    :let [{:keys [open broken deferred regression]
                           :or {open 0 broken 0 deferred 0 regression 0}} (counts es)]]
              (println (format "* %s (open %d, broken %d, parked %d, regressions %d)"
                               c open broken deferred regression))
              (doseq [[r label] [[:regression "Regressions (ledger says :ported)"]
                                 [:broken "Broken - bound to a void command"]
                                 [:open "Open - needs a verdict"]
                                 [:deferred "Parked (:deferred)"]
                                 [:dropped "Dropped"]
                                 [:improved "Improved (deliberate deviations)"]
                                 [:lab-only "Lab-only additions"]]
                      :let [sel (filter #(= r (:resolution %)) es)]
                      :when (seq sel)]
                (println (str "** " label))
                (doseq [e sel]
                  (println (org-entry e)))))))
    (println "cluster                     open  broken  parked  regr")
    (doseq [[c es] (sort-by key by-cluster)
            :let [{:keys [open broken deferred regression]
                   :or {open 0 broken 0 deferred 0 regression 0}} (counts es)]
            :when (pos? (+ open broken deferred regression))]
      (println (format "%-26s %5d %7d %7d %5d" c open broken deferred regression)))
    (println (format "total: %d open, %d broken, %d parked, %d regressions, %d resolved, %d lab-only"
                     (:open total 0) (:broken total 0) (:deferred total 0)
                     (:regression total 0)
                     (+ (:dropped total 0) (:improved total 0)) (:lab-only total 0)))
    (println "report:" report-file)
    (System/exit (if (pos? (:regression total 0)) 1 0))))

(-main)
